export default [
  {
    "childs": [
      {
        "childs": [
          {
            "childs": [],
            "code": "100101",
            "created": "2020-02-22 19:01:40",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 200,
            "qa_standard": "<p><img src=\"https://cdn-durian-dev.pgyscm.com/systemClass/0188e1dc-68cc-11ea-9659-5254005309a2\"><img src=\"https://cdn-durian-dev.pgyscm.com/systemClass/056c5e46-68cc-11ea-9659-5254005309a2\"></p>",
            "rank": 0,
            "remark": "222",
            "title": "苹果",
            "top_code": "1001",
            "updated": "2020-05-18 11:22:10"
          },
          {
            "childs": [],
            "code": "100102",
            "created": "2020-02-22 19:01:52",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "梨",
            "top_code": "1001",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100103",
            "created": "2020-02-22 19:02:17",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "山楂",
            "top_code": "1001",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100104",
            "created": "2020-02-22 19:02:29",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "枇杷",
            "top_code": "1001",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100105",
            "created": "2020-02-22 20:59:37",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "柿子",
            "top_code": "1001",
            "updated": "2020-03-06 15:08:30"
          }
        ],
        "code": "1001",
        "created": "2020-02-22 18:51:22",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "仁果类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:25"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "100201",
            "created": "2020-02-22 19:02:37",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 100,
            "qa_standard": "<p>1111</p>",
            "rank": 0,
            "remark": "",
            "title": "西瓜",
            "top_code": "1002",
            "updated": "2020-05-22 09:58:17"
          },
          {
            "childs": [],
            "code": "100202",
            "created": "2020-02-22 19:02:45",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "蜜瓜",
            "top_code": "1002",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100203",
            "created": "2020-02-22 19:03:06",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "甜瓜",
            "top_code": "1002",
            "updated": "2020-03-06 15:08:30"
          }
        ],
        "code": "1002",
        "created": "2020-02-22 18:51:39",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "瓜果类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:25"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "100301",
            "created": "2020-02-22 20:48:46",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "葡萄",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100302",
            "created": "2020-02-22 20:49:09",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "蓝莓",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100303",
            "created": "2020-02-22 20:49:28",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "草莓",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100304",
            "created": "2020-02-22 21:04:52",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "提子",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100305",
            "created": "2020-02-22 21:05:13",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "圣女果",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:30"
          },
          {
            "childs": [],
            "code": "100306",
            "created": "2020-02-22 21:05:21",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "姑娘果",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100307",
            "created": "2020-02-22 21:05:39",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "桑葚",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100308",
            "created": "2020-02-22 21:06:07",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "奇异果",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100309",
            "created": "2020-02-22 21:09:26",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "杨梅",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100310",
            "created": "2020-02-22 21:15:35",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "石榴",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100311",
            "created": "2020-02-26 22:47:57",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "水果黄瓜",
            "top_code": "1003",
            "updated": "2020-03-06 15:08:31"
          }
        ],
        "code": "1003",
        "created": "2020-02-22 18:51:55",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "浆果类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:25"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "100401",
            "created": "2020-02-22 21:08:55",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "桃",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100402",
            "created": "2020-02-22 21:09:05",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "李",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100403",
            "created": "2020-02-22 21:09:13",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "杏",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100404",
            "created": "2020-02-22 21:09:53",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "梅",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100405",
            "created": "2020-02-22 21:10:19",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "枣类",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100406",
            "created": "2020-02-22 21:10:35",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "樱桃",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100407",
            "created": "2020-02-22 21:10:48",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "车厘子",
            "top_code": "1004",
            "updated": "2020-03-06 15:08:31"
          }
        ],
        "code": "1004",
        "created": "2020-02-22 18:52:51",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "核果类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:26"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "100501",
            "created": "2020-02-22 21:02:35",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 500,
            "qa_standard": "<p>111</p>",
            "rank": 0,
            "remark": "",
            "title": "柑",
            "top_code": "1005",
            "updated": "2020-05-22 09:59:32"
          },
          {
            "childs": [],
            "code": "100502",
            "created": "2020-02-22 21:06:54",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "桔",
            "top_code": "1005",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100503",
            "created": "2020-02-22 21:07:16",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "橙",
            "top_code": "1005",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100504",
            "created": "2020-02-22 21:07:31",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "柚",
            "top_code": "1005",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100505",
            "created": "2020-02-22 21:07:51",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "柠檬",
            "top_code": "1005",
            "updated": "2020-03-06 15:08:31"
          }
        ],
        "code": "1005",
        "created": "2020-02-22 18:53:09",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "柑橘橙类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:26"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "100601",
            "created": "2020-02-22 21:02:26",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "芒果",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100602",
            "created": "2020-02-22 21:08:43",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "香蕉",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:31"
          },
          {
            "childs": [],
            "code": "100603",
            "created": "2020-02-22 21:12:20",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "荔枝",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100604",
            "created": "2020-02-22 21:12:29",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "榴莲",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100605",
            "created": "2020-02-22 21:12:35",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "山竹",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100606",
            "created": "2020-02-22 21:12:42",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "龙眼",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100607",
            "created": "2020-02-22 21:12:52",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "火龙果",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100608",
            "created": "2020-02-22 21:13:00",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "菠萝蜜",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100609",
            "created": "2020-02-22 21:13:08",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "椰青",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100610",
            "created": "2020-02-22 21:13:21",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "释迦",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100611",
            "created": "2020-02-22 21:13:27",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "菠萝",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100612",
            "created": "2020-02-22 21:13:34",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "凤梨",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100613",
            "created": "2020-02-22 21:13:45",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "木瓜",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100614",
            "created": "2020-02-22 21:13:52",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "莲雾",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100615",
            "created": "2020-02-22 21:14:04",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "红毛丹",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100616",
            "created": "2020-02-22 21:15:46",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "榴莲蜜",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100617",
            "created": "2020-02-22 21:15:54",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "牛油果",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100618",
            "created": "2020-02-22 21:16:11",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "杨桃",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100619",
            "created": "2020-02-22 21:16:19",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "百香果",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100620",
            "created": "2020-02-22 21:16:42",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "番石榴",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100621",
            "created": "2020-02-22 21:16:57",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "甘蔗",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "100622",
            "created": "2020-02-22 21:18:27",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "雪莲果",
            "top_code": "1006",
            "updated": "2020-03-06 15:08:32"
          }
        ],
        "code": "1006",
        "created": "2020-02-22 19:51:16",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "热带类",
        "top_code": "10",
        "updated": "2020-03-06 15:08:26"
      },
      {
        "childs": [],
        "code": "1007",
        "created": "2020-05-21 10:07:15",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "草莓",
        "top_code": "10",
        "updated": "2020-05-21 10:07:15"
      }
    ],
    "code": "10",
    "created": "2020-02-22 18:49:57",
    "has_produce_date": false,
    "is_deleted": false,
    "qa_rate": 0,
    "qa_standard": null,
    "rank": 0,
    "remark": "",
    "title": "水果",
    "top_code": "",
    "updated": "2020-02-22 18:49:57"
  },
  {
    "childs": [
      {
        "childs": [
          {
            "childs": [],
            "code": "110101",
            "created": "2020-02-22 19:35:17",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "鲜奶",
            "top_code": "1101",
            "updated": "2020-03-06 15:08:32"
          },
          {
            "childs": [],
            "code": "110102",
            "created": "2020-02-22 21:23:04",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "酸奶",
            "top_code": "1101",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110103",
            "created": "2020-02-22 21:24:10",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "奶酪",
            "top_code": "1101",
            "updated": "2020-03-06 15:08:33"
          }
        ],
        "code": "1101",
        "created": "2020-02-22 18:55:08",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "奶制品",
        "top_code": "11",
        "updated": "2020-03-06 15:08:28"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110201",
            "created": "2020-02-22 21:30:12",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "坚果",
            "top_code": "1102",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110202",
            "created": "2020-02-22 21:30:21",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "干果",
            "top_code": "1102",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110203",
            "created": "2020-02-22 21:30:55",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "炒货",
            "top_code": "1102",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110204",
            "created": "2020-02-22 21:31:47",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "干菜",
            "top_code": "1102",
            "updated": "2020-03-06 15:08:33"
          }
        ],
        "code": "1102",
        "created": "2020-02-22 18:55:38",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "干货",
        "top_code": "11",
        "updated": "2020-03-06 15:08:28"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110301",
            "created": "2020-02-22 21:32:27",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "卤制品",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110302",
            "created": "2020-02-22 21:38:42",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "粽子",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110303",
            "created": "2020-02-26 22:39:18",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "肉制品",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110304",
            "created": "2020-02-26 22:39:27",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "鱼制品",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110305",
            "created": "2020-02-26 22:39:35",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "辣条",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110306",
            "created": "2020-02-26 22:39:43",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "麻辣",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110307",
            "created": "2020-02-26 22:39:52",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "豆制品",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110308",
            "created": "2020-02-26 22:40:05",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "蛋制品",
            "top_code": "1103",
            "updated": "2020-03-06 15:08:33"
          }
        ],
        "code": "1103",
        "created": "2020-02-22 18:57:10",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "熟食",
        "top_code": "11",
        "updated": "2020-03-06 15:08:28"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110401",
            "created": "2020-02-22 21:33:44",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "面包",
            "top_code": "1104",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110402",
            "created": "2020-02-22 21:33:57",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "糕点",
            "top_code": "1104",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110403",
            "created": "2020-02-22 21:34:03",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "饼干",
            "top_code": "1104",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110404",
            "created": "2020-02-22 21:38:00",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "月饼",
            "top_code": "1104",
            "updated": "2020-03-06 15:08:33"
          }
        ],
        "code": "1104",
        "created": "2020-02-22 18:56:56",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "面点",
        "top_code": "11",
        "updated": "2020-03-06 15:08:29"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110501",
            "created": "2020-02-22 21:35:50",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "果汁",
            "top_code": "1105",
            "updated": "2020-03-06 15:08:33"
          },
          {
            "childs": [],
            "code": "110502",
            "created": "2020-02-22 21:35:59",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "水",
            "top_code": "1105",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "110503",
            "created": "2020-02-22 21:36:07",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "茶饮",
            "top_code": "1105",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "110504",
            "created": "2020-02-22 21:36:32",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "碳酸饮料",
            "top_code": "1105",
            "updated": "2020-03-06 15:08:34"
          }
        ],
        "code": "1105",
        "created": "2020-02-22 21:27:04",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "软饮",
        "top_code": "11",
        "updated": "2020-03-06 15:08:29"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110601",
            "created": "2020-02-22 21:35:39",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "休闲食品",
            "top_code": "1106",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "110602",
            "created": "2020-02-22 21:36:39",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "糖果",
            "top_code": "1106",
            "updated": "2020-03-06 15:08:34"
          }
        ],
        "code": "1106",
        "created": "2020-02-22 21:34:57",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "零食",
        "top_code": "11",
        "updated": "2020-03-06 15:08:29"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "110701",
            "created": "2020-02-26 22:41:46",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "方便速食",
            "top_code": "1107",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "110702",
            "created": "2020-02-26 22:42:06",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "冷冻速食",
            "top_code": "1107",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "110703",
            "created": "2020-02-26 22:42:17",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "半成品速食",
            "top_code": "1107",
            "updated": "2020-03-06 15:08:34"
          }
        ],
        "code": "1107",
        "created": "2020-02-26 22:41:27",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "速食",
        "top_code": "11",
        "updated": "2020-03-06 15:08:29"
      }
    ],
    "code": "11",
    "created": "2020-02-22 18:54:01",
    "has_produce_date": false,
    "is_deleted": false,
    "qa_rate": 0,
    "qa_standard": null,
    "rank": 0,
    "remark": "",
    "title": "副食",
    "top_code": "",
    "updated": "2020-02-22 19:58:47"
  },
  {
    "childs": [
      {
        "childs": [
          {
            "childs": [],
            "code": "120101",
            "created": "2020-02-26 22:44:56",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "果切盒",
            "top_code": "1201",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "120102",
            "created": "2020-02-26 22:45:46",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "封带",
            "top_code": "1201",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "120103",
            "created": "2020-02-26 23:20:16",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "塑料袋",
            "top_code": "1201",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "120104",
            "created": "2020-02-26 23:20:23",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "保鲜膜",
            "top_code": "1201",
            "updated": "2020-03-06 15:08:34"
          }
        ],
        "code": "1201",
        "created": "2020-02-22 18:58:59",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "塑料制品",
        "top_code": "12",
        "updated": "2020-03-06 15:08:29"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "120201",
            "created": "2020-02-26 22:45:29",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 0,
            "qa_standard": null,
            "rank": 0,
            "remark": "",
            "title": "贴纸",
            "top_code": "1202",
            "updated": "2020-03-06 15:08:34"
          }
        ],
        "code": "1202",
        "created": "2020-02-22 18:59:10",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "纸制品",
        "top_code": "12",
        "updated": "2020-03-06 15:08:29"
      },
      {
        "childs": [
          {
            "childs": [],
            "code": "120401",
            "created": "2020-02-26 22:45:06",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 80,
            "qa_standard": "<p>测试用途</p>",
            "rank": 0,
            "remark": "",
            "title": "果篮",
            "top_code": "1204",
            "updated": "2020-03-06 15:08:34"
          },
          {
            "childs": [],
            "code": "120402",
            "created": "2020-05-19 14:17:49",
            "has_produce_date": false,
            "is_deleted": false,
            "qa_rate": 120,
            "qa_standard": "<p>阿顺撒多付微微儿</p>",
            "rank": 0,
            "remark": "12省份",
            "title": "货架",
            "top_code": "1204",
            "updated": "2020-05-19 14:17:58"
          }
        ],
        "code": "1204",
        "created": "2020-02-22 18:59:52",
        "has_produce_date": false,
        "is_deleted": false,
        "qa_rate": 0,
        "qa_standard": null,
        "rank": 0,
        "remark": "",
        "title": "木制品",
        "top_code": "12",
        "updated": "2020-03-06 15:08:30"
      }
    ],
    "code": "12",
    "created": "2020-02-22 18:54:19",
    "has_produce_date": true,
    "is_deleted": false,
    "qa_rate": 0,
    "qa_standard": null,
    "rank": 0,
    "remark": "1111",
    "title": "包装辅材",
    "top_code": "",
    "updated": "2020-05-18 21:06:08"
  }
]